# views.yaml - SQL View Definitions for Complex UI Components
#
# This file defines Dapper-based read-only views for Blazor/Radzen components.
# Each view corresponds to a SQL query file and generates a C# DTO class.
#
# Generation command: make run-view-pipeline
# Generated output: DotNetWebApp.Models/ViewModels/*.cs
#
# Partial Class Pattern:
#   - Generated files: {Name}.generated.cs (overwritten on regeneration)
#   - Manual files: {Name}.cs (optional, user-maintained, never overwritten)
#
# Example user extension (ProductSalesView.cs):
#   public partial class ProductSalesView
#   {
#       public string FormattedRevenue => TotalRevenue.ToString("C");
#   }

views:
  - name: ProductSalesView
    description: "Product sales summary with category and order totals"
    sql_file: "sql/views/ProductSalesView.sql"
    generate_partial: true
    parameters:
      - name: TopN
        type: int
        nullable: false
        default: "10"
        validation:
          required: true
          range: [1, 1000]
    properties:
      - name: Id
        type: int
        nullable: false
      - name: Name
        type: string
        nullable: false
        max_length: 100
      - name: Price
        type: decimal
        nullable: false
      - name: CategoryName
        type: string
        nullable: true
        max_length: 100
      - name: TotalSold
        type: int
        nullable: false
      - name: TotalRevenue
        type: decimal
        nullable: false
