// <auto-generated />
using System;
using DotNetWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317234153_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetWebApp.Models.Generated.WEBAPP.Customers", b =>
                {
                    b.Property<int>("cu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cu_id"));

                    b.Property<bool>("cu_active")
                        .HasColumnType("bit");

                    b.Property<string>("cu_city")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("cu_code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("cu_contact")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("cu_country")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("cu_created")
                        .HasColumnType("datetime2");

                    b.Property<string>("cu_email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("cu_name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("cu_notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("cu_state")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("cu_street")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("cu_zip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("cu_id");

                    b.ToTable("customers", "dbo");
                });

            modelBuilder.Entity("DotNetWebApp.Models.Generated.WEBAPP.Inventory", b =>
                {
                    b.Property<int>("in_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("in_id"));

                    b.Property<DateTime?>("in_expiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("in_lot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("in_product_id")
                        .HasColumnType("int");

                    b.Property<int>("in_qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("in_received")
                        .HasColumnType("datetime2");

                    b.Property<int>("in_reserved")
                        .HasColumnType("int");

                    b.Property<int>("in_warehouse_id")
                        .HasColumnType("int");

                    b.HasKey("in_id");

                    b.ToTable("inventory", "dbo");
                });

            modelBuilder.Entity("DotNetWebApp.Models.Generated.WEBAPP.Order_lines", b =>
                {
                    b.Property<int>("ol_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ol_id"));

                    b.Property<string>("ol_notes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ol_order_id")
                        .HasColumnType("int");

                    b.Property<decimal>("ol_price")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("ol_price");

                    b.Property<int>("ol_product_id")
                        .HasColumnType("int");

                    b.Property<int>("ol_qty")
                        .HasColumnType("int");

                    b.Property<decimal>("ol_total")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("ol_total");

                    b.HasKey("ol_id");

                    b.ToTable("order_lines", "dbo");
                });

            modelBuilder.Entity("DotNetWebApp.Models.Generated.WEBAPP.Orders", b =>
                {
                    b.Property<int>("or_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("or_id"));

                    b.Property<DateTime>("or_created")
                        .HasColumnType("datetime2");

                    b.Property<int>("or_customer_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("or_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("or_notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("or_number")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("or_ship_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("or_status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("or_total")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("or_total");

                    b.Property<int>("or_warehouse_id")
                        .HasColumnType("int");

                    b.HasKey("or_id");

                    b.ToTable("orders", "dbo");
                });

            modelBuilder.Entity("DotNetWebApp.Models.Generated.WEBAPP.Products", b =>
                {
                    b.Property<int>("pr_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pr_id"));

                    b.Property<bool>("pr_active")
                        .HasColumnType("bit");

                    b.Property<string>("pr_category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("pr_code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("pr_cost")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("pr_cost");

                    b.Property<DateTime>("pr_created")
                        .HasColumnType("datetime2");

                    b.Property<string>("pr_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("pr_notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("pr_price")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("pr_price");

                    b.Property<string>("pr_unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("pr_updated")
                        .HasColumnType("datetime2");

                    b.HasKey("pr_id");

                    b.ToTable("products", "dbo");
                });

            modelBuilder.Entity("DotNetWebApp.Models.Generated.WEBAPP.Units_of_measure", b =>
                {
                    b.Property<int>("um_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("um_id"));

                    b.Property<string>("um_abbrev")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("um_name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("um_id");

                    b.ToTable("units_of_measure", "dbo");
                });

            modelBuilder.Entity("DotNetWebApp.Models.Generated.WEBAPP.Vendors", b =>
                {
                    b.Property<int>("ve_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ve_id"));

                    b.Property<bool>("ve_active")
                        .HasColumnType("bit");

                    b.Property<string>("ve_city")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ve_code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ve_contact")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ve_name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ve_notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ve_phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ve_state")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ve_street")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ve_zip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ve_id");

                    b.ToTable("vendors", "dbo");
                });

            modelBuilder.Entity("DotNetWebApp.Models.Generated.WEBAPP.Warehouses", b =>
                {
                    b.Property<int>("wa_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("wa_id"));

                    b.Property<bool>("wa_active")
                        .HasColumnType("bit");

                    b.Property<string>("wa_city")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("wa_code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("wa_name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("wa_state")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("wa_street")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("wa_zip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("wa_id");

                    b.ToTable("warehouses", "dbo");
                });

            modelBuilder.Entity("DotNetWebApp.Models.Generated.WEBAPPMisc.AcidCorrection", b =>
                {
                    b.Property<int>("ac_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ac_id"));

                    b.Property<float?>("AcidCorrectionValue")
                        .HasColumnType("real")
                        .HasColumnName("AcidCorrection");

                    b.Property<double>("PercentAcid")
                        .HasColumnType("float");

                    b.HasKey("ac_id");

                    b.ToTable("acidcorrection", "dbo");
                });

            modelBuilder.Entity("DotNetWebApp.Models.Generated.WEBAPPMisc.BrixChart", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<float>("Brix")
                        .HasColumnType("real");

                    b.Property<double?>("LbPerGallon")
                        .HasColumnType("float");

                    b.Property<double?>("PoundSolid")
                        .HasColumnType("float");

                    b.Property<double?>("RefractiveIndex")
                        .HasColumnType("float");

                    b.Property<double?>("SpecificGravity")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("brixchart", "dbo");
                });

            modelBuilder.Entity("DotNetWebApp.Models.Generated.WEBAPPMisc.Webapp_allocate", b =>
                {
                    b.Property<int>("all_index")
                        .HasColumnType("int");

                    b.Property<decimal>("all_id")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("all_id");

                    b.Property<long>("all_ordernum")
                        .HasColumnType("bigint");

                    b.Property<string>("all_codenum")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("all_userlot")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("all_carrier")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("all_chr1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("all_chr2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("all_chr3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("all_chr4")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("all_chr5")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("all_chr6")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("all_chx1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("all_chx2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("all_chx3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("all_chx4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("all_chx5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("all_chx6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("all_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("all_date1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("all_date2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("all_date3")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("all_date4")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("all_date5")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("all_date6")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("all_dec1")
                        .HasColumnType("decimal(18, 8)")
                        .HasColumnName("all_dec1");

                    b.Property<decimal?>("all_dec3")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("all_dec3");

                    b.Property<decimal?>("all_dec4")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("all_dec4");

                    b.Property<decimal?>("all_dec5")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("all_dec5");

                    b.Property<decimal?>("all_dec6")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("all_dec6");

                    b.Property<string>("all_description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("all_gwt")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("all_gwt");

                    b.Property<int?>("all_int1")
                        .HasColumnType("int");

                    b.Property<int?>("all_int2")
                        .HasColumnType("int");

                    b.Property<int?>("all_int3")
                        .HasColumnType("int");

                    b.Property<int?>("all_int4")
                        .HasColumnType("int");

                    b.Property<int?>("all_int5")
                        .HasColumnType("int");

                    b.Property<int?>("all_int6")
                        .HasColumnType("int");

                    b.Property<string>("all_notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("all_num1")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("all_num1");

                    b.Property<decimal?>("all_num2")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("all_num2");

                    b.Property<decimal?>("all_num3")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("all_num3");

                    b.Property<decimal?>("all_nwt")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("all_nwt");

                    b.Property<int?>("all_pick")
                        .HasColumnType("int");

                    b.Property<int?>("all_qty")
                        .HasColumnType("int");

                    b.Property<string>("all_status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("all_um")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("all_index", "all_id", "all_ordernum", "all_codenum", "all_userlot");

                    b.ToTable("webapp_allocate", "dbo");
                });

            modelBuilder.Entity("DotNetWebApp.Models.Generated.WEBAPPMisc.Webapp_dmstech", b =>
                {
                    b.Property<int>("gs_index")
                        .HasColumnType("int");

                    b.Property<decimal>("gs_id")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("gs_id");

                    b.Property<int>("gs_type")
                        .HasColumnType("int");

                    b.Property<string>("gs_chr1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gs_chr2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gs_chr3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gs_chr4")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gs_chr5")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gs_chx1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gs_chx2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gs_chx3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("gs_consignor_sig")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("gs_date1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("gs_date2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("gs_date3")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("gs_driver_sig")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("gs_int1")
                        .HasColumnType("int");

                    b.Property<int?>("gs_int2")
                        .HasColumnType("int");

                    b.Property<int?>("gs_int3")
                        .HasColumnType("int");

                    b.Property<string>("gs_security2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("gs_index", "gs_id", "gs_type", "gs_chr1");

                    b.ToTable("webapp_dmstech", "dbo");
                });

            modelBuilder.Entity("DotNetWebApp.Models.Generated.WEBAPPMisc.Webapp_lock", b =>
                {
                    b.Property<int>("gl_index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("gl_index"));

                    b.Property<int>("gl_id")
                        .HasColumnType("int");

                    b.Property<long>("gl_ordnum")
                        .HasColumnType("bigint");

                    b.Property<string>("gl_partnum")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gl_userlot")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gl_chr1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gl_chr2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gl_chx1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gl_chx2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("gl_date1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("gl_date2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("gl_date3")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("gl_date4")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("gl_datel")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("gl_dec1")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("gl_dec1");

                    b.Property<decimal?>("gl_dec2")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("gl_dec2");

                    b.Property<int?>("gl_int1")
                        .HasColumnType("int");

                    b.Property<int?>("gl_int2")
                        .HasColumnType("int");

                    b.Property<string>("gl_notes1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gl_notes2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("gl_qty1")
                        .HasColumnType("int");

                    b.Property<int?>("gl_qty2")
                        .HasColumnType("int");

                    b.Property<int?>("gl_qty3")
                        .HasColumnType("int");

                    b.Property<string>("gl_username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("gl_index", "gl_id", "gl_ordnum", "gl_partnum", "gl_userlot");

                    b.ToTable("webapp_lock", "dbo");
                });

            modelBuilder.Entity("DotNetWebApp.Models.Generated.WEBAPPMisc.Webapp_scheduler", b =>
                {
                    b.Property<int>("gs_index")
                        .HasColumnType("int");

                    b.Property<decimal>("gs_id")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("gs_id");

                    b.Property<long>("gs_ordnum")
                        .HasColumnType("bigint");

                    b.Property<string>("gs_appid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gs_assembler")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("gs_assemblerin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("gs_assemblerout")
                        .HasColumnType("datetime2");

                    b.Property<string>("gs_auditor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("gs_auditorin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("gs_auditorout")
                        .HasColumnType("datetime2");

                    b.Property<string>("gs_carrier")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gs_chr1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gs_chr2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gs_chr3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gs_chr4")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gs_chr5")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gs_chr6")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gs_company")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("gs_date1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("gs_date2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("gs_date3")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("gs_date4")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("gs_date5")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("gs_date6")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("gs_datechkin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("gs_dateend")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("gs_datestart")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("gs_dec1")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("gs_dec1");

                    b.Property<decimal?>("gs_dec2")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("gs_dec2");

                    b.Property<decimal?>("gs_dec3")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("gs_dec3");

                    b.Property<decimal?>("gs_dec4")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("gs_dec4");

                    b.Property<decimal?>("gs_dec5")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("gs_dec5");

                    b.Property<long?>("gs_dec6")
                        .HasColumnType("bigint");

                    b.Property<string>("gs_dock")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<TimeSpan?>("gs_dockm")
                        .HasColumnType("time");

                    b.Property<string>("gs_driver")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gs_forkop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("gs_gwt")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("gs_gwt");

                    b.Property<byte[]>("gs_img1")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("gs_img2")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("gs_img3")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("gs_img4")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("gs_img5")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("gs_img6")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool?>("gs_log1")
                        .HasColumnType("bit");

                    b.Property<bool?>("gs_log2")
                        .HasColumnType("bit");

                    b.Property<bool?>("gs_log3")
                        .HasColumnType("bit");

                    b.Property<bool?>("gs_log4")
                        .HasColumnType("bit");

                    b.Property<bool?>("gs_log5")
                        .HasColumnType("bit");

                    b.Property<bool?>("gs_log6")
                        .HasColumnType("bit");

                    b.Property<string>("gs_notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("gs_notesict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("gs_num1")
                        .HasColumnType("bigint");

                    b.Property<long?>("gs_num2")
                        .HasColumnType("bigint");

                    b.Property<long?>("gs_num3")
                        .HasColumnType("bigint");

                    b.Property<long?>("gs_num4")
                        .HasColumnType("bigint");

                    b.Property<long?>("gs_num5")
                        .HasColumnType("bigint");

                    b.Property<long?>("gs_num6")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("gs_nwt")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("gs_nwt");

                    b.Property<int?>("gs_pallets")
                        .HasColumnType("int");

                    b.Property<string>("gs_picker")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("gs_pickerin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("gs_pickerout")
                        .HasColumnType("datetime2");

                    b.Property<int?>("gs_pronum")
                        .HasColumnType("int");

                    b.Property<string>("gs_status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("gs_index", "gs_id", "gs_ordnum", "gs_appid");

                    b.ToTable("webapp_scheduler", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
