// <auto-generated>
//     This code was generated by ViewModelGenerator on 2026-01-27 06:00:46 UTC.
//     SQL Source: sql/views/ProductSalesView.sql
//
//     DO NOT EDIT - changes will be overwritten on regeneration.
//     To add custom logic, create a separate ProductSalesView.cs file with a partial class.
// </auto-generated>

#nullable enable

using System;
using System.ComponentModel.DataAnnotations;

namespace DotNetWebApp.Models.ViewModels
{
    /// <summary>
    /// Product sales summary with category and order totals
    /// </summary>
    /// <remarks>
    /// SQL Source: sql/views/ProductSalesView.sql
    /// Parameters:
    ///   - @TopN (int) = 10
    /// </remarks>
    public partial class ProductSalesView
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(100)]
        public string Name { get; set; } = null!;

        public decimal Price { get; set; }

        [MaxLength(100)]
        public string? CategoryName { get; set; }

        public int TotalSold { get; set; }

        public decimal TotalRevenue { get; set; }

    }

    /// <summary>
    /// Parameters for ProductSalesView view query.
    /// </summary>
    public partial class ProductSalesViewParameters
    {
        [Required]
        [Range(1, 1000)]
        public int TopN { get; set; } = 10;

    }
}
