-- GAI Database DDL converted from SQL Server to SQLite
-- Generated by SQL Server to SQLite DDL Converter
-- Based on MSSQLToSQLite and SqlCeToolbox conversion patterns
-- Original source: GAI_DDL_SCRIPT.sql

PRAGMA foreign_keys = ON;

/* DISABLED: __EFMigrationsHistory is created automatically by EF Core.
-- Table: __EFMigrationsHistory
CREATE TABLE __EFMigrationsHistory (
    MigrationId TEXT NOT NULL,
    ProductVersion TEXT NOT NULL
);
END DISABLED */

-- Table: AcidCorrection
CREATE TABLE AcidCorrection (
    ac_id INTEGER PRIMARY KEY AUTOINCREMENT,
    PercentAcid REAL NOT NULL,
    AcidCorrection REAL
);

-- Table: BrixChart
CREATE TABLE BrixChart (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    RefractiveIndex REAL,
    Brix REAL NOT NULL,
    SpecificGravity REAL,
    LbPerGallon REAL,
    PoundSolid REAL
);

-- Table: gai_allocate
CREATE TABLE gai_allocate (
    all_index INTEGER PRIMARY KEY AUTOINCREMENT,
    all_id NUMERIC NOT NULL,
    all_ordernum INTEGER NOT NULL,
    all_codenum TEXT NOT NULL,
    all_userlot TEXT NOT NULL,
    all_qty INTEGER,
    all_pick INTEGER,
    all_date TEXT,
    all_chr1 TEXT,
    all_chr2 TEXT,
    all_chr3 TEXT,
    all_chx1 TEXT,
    all_chx2 TEXT,
    all_chx3 TEXT,
    all_int1 INTEGER,
    all_int2 INTEGER,
    all_int3 INTEGER,
    all_num1 NUMERIC,
    all_num2 NUMERIC,
    all_num3 NUMERIC,
    all_date1 TEXT,
    all_date2 TEXT,
    all_date3 TEXT,
    all_dec1 NUMERIC,
    all_description TEXT,
    all_um TEXT,
    all_chr4 TEXT,
    all_chr5 TEXT,
    all_chr6 TEXT,
    all_chx4 TEXT,
    all_chx5 TEXT,
    all_chx6 TEXT,
    all_int4 INTEGER,
    all_int5 INTEGER,
    all_int6 INTEGER,
    all_dec4 NUMERIC,
    all_dec5 NUMERIC,
    all_dec6 NUMERIC,
    all_date4 TEXT,
    all_date5 TEXT,
    all_date6 TEXT,
    all_dec3 NUMERIC,
    all_nwt NUMERIC,
    all_gwt NUMERIC,
    all_status TEXT,
    all_carrier TEXT,
    all_notes TEXT
);

-- Table: gai_allocateaudit
CREATE TABLE gai_allocateaudit (
    ala_index INTEGER PRIMARY KEY AUTOINCREMENT,
    ala_id INTEGER NOT NULL,
    ala_ordernum INTEGER NOT NULL,
    ala_status INTEGER NOT NULL,
    ala_codenum TEXT NOT NULL,
    ala_userlot TEXT NOT NULL,
    ala_cw NUMERIC,
    ala_expdate TEXT,
    ala_mfgdate TEXT,
    ala_qtywarehouse INTEGER,
    ala_qtyallocated INTEGER,
    ala_qtyremain INTEGER,
    ala_country TEXT,
    ala_location TEXT,
    ala_typewarning TEXT,
    ala_chr1 TEXT,
    ala_chr2 TEXT,
    ala_chr3 TEXT,
    ala_chx1 TEXT,
    ala_chx2 TEXT,
    ala_chx3 TEXT,
    ala_num1 NUMERIC,
    ala_num2 NUMERIC,
    ala_num3 NUMERIC,
    ala_dec1 NUMERIC,
    ala_dec2 NUMERIC,
    ala_dec3 NUMERIC,
    ala_date1 TEXT,
    ala_date2 TEXT,
    ala_date3 TEXT,
    ala_img1 BLOB,
    ala_img2 BLOB,
    ala_img3 BLOB
);

-- Table: gai_bol
CREATE TABLE gai_bol (
    bol_index INTEGER NOT NULL,
    bol_id NUMERIC NOT NULL,
    bol_ordernum INTEGER NOT NULL,
    bol_appid TEXT NOT NULL,
    bol_date TEXT NOT NULL,
    bol_condition TEXT,
    bol_temp TEXT,
    bol_clean TEXT,
    bol_pests TEXT,
    bol_odors TEXT,
    bol_padlocked TEXT,
    bol_itype TEXT,
    bol_tnumber TEXT,
    bol_tnotes TEXT,
    bol_tcheckedby TEXT,
    bol_scheddd TEXT,
    bol_deliveryd TEXT,
    bol_pod TEXT,
    bol_problnumber TEXT,
    bol_appcontactph TEXT,
    bol_appcontactname TEXT,
    bol_pallets TEXT,
    bol_drivername TEXT,
    bol_last3prod TEXT,
    bol_wtype TEXT,
    bol_chr1 TEXT,
    bol_chr2 TEXT,
    bol_chr3 TEXT,
    bol_chx1 TEXT,
    bol_chx2 TEXT,
    bol_chx3 TEXT,
    bol_date1 TEXT,
    bol_date2 TEXT,
    bol_num1 INTEGER,
    bol_num2 INTEGER,
    bol_img1 INTEGER,
    bol_img2 INTEGER,
    bol_img3 INTEGER
);

-- Table: gai_bolapp
CREATE TABLE gai_bolapp (
    bol_index INTEGER PRIMARY KEY AUTOINCREMENT,
    bol_id NUMERIC NOT NULL,
    bol_appid TEXT NOT NULL,
    bol_tb11 TEXT,
    bol_tb31 TEXT,
    bol_tb28 TEXT,
    bol_tb29 TEXT,
    bol_tb30 TEXT,
    bol_tb14 TEXT,
    bol_tb16 TEXT,
    bol_tb17 TEXT,
    bol_tb23 TEXT,
    bol_tb24 TEXT,
    bol_tb25 TEXT,
    bol_tb26 TEXT,
    bol_tb27 TEXT,
    bol_tb19 TEXT,
    bol_tb20 TEXT,
    bol_tb35 TEXT,
    bol_tb32 TEXT,
    bol_tb34 TEXT,
    bol_tb36 TEXT,
    bol_chr1 TEXT,
    bol_chr2 TEXT,
    bol_chr3 TEXT,
    bol_chx1 TEXT,
    bol_chx2 TEXT,
    bol_chx3 TEXT,
    bol_img1 BLOB,
    bol_img2 BLOB,
    bol_img3 BLOB,
    bol_img4 BLOB,
    bol_img5 BLOB
);

-- Table: gai_boldetail
CREATE TABLE gai_boldetail (
    gb_bol INTEGER,
    gb_npcs NUMERIC,
    gb_container TEXT,
    gb_codenum TEXT,
    gb_description TEXT,
    gb_netw NUMERIC,
    gb_grossw NUMERIC,
    gb_class TEXT
);

-- Table: gai_bolheader
CREATE TABLE gai_bolheader (
    gb_bol INTEGER,
    gb_carrierno INTEGER,
    gb_pono TEXT,
    gb_carrier TEXT,
    gb_at TEXT,
    gb_at1 TEXT,
    gb_from1 TEXT,
    gb_consigned TEXT,
    gb_destination TEXT,
    gb_tpc INTEGER,
    gb_twl NUMERIC,
    gb_freight1 TEXT,
    gb_type1 TEXT,
    gb_loadedby TEXT,
    gb_palletsin INTEGER,
    gb_freepest TEXT,
    gb_trailerclean TEXT,
    gb_trailerintact TEXT,
    gb_sealno TEXT,
    gb_temp1 TEXT,
    gb_palletsout INTEGER,
    gb_acceptableodor TEXT,
    gb_padlocker TEXT,
    gb_approvedby TEXT,
    gb_temp2 TEXT,
    gb_initials TEXT,
    gb_notes TEXT,
    gb_shipper TEXT,
    gb_agent TEXT,
    gb_postoffice TEXT,
    gb_chr1 TEXT,
    gb_chr2 TEXT,
    gb_chr3 TEXT,
    gb_chr4 TEXT,
    gb_chr5 TEXT,
    gb_num1 INTEGER,
    gb_num2 INTEGER,
    gb_num3 INTEGER,
    gb_dec1 NUMERIC,
    gb_dec2 NUMERIC,
    gb_dec3 NUMERIC,
    gb_scac TEXT,
    gb_delcarrier TEXT,
    gb_carvei TEXT,
    gb_carvein TEXT
);

-- Table: gai_combob
CREATE TABLE gai_combob (
    cb_index INTEGER PRIMARY KEY AUTOINCREMENT,
    cb_type INTEGER NOT NULL,
    cb_ulogin TEXT NOT NULL,
    cb_chr1 TEXT,
    cb_chr2 TEXT,
    cb_chr3 TEXT,
    cb_chx1 TEXT,
    cb_chx2 TEXT,
    cb_int1 INTEGER,
    cb_int2 INTEGER,
    cb_int3 INTEGER,
    cb_date1 TEXT,
    cb_date2 TEXT,
    cb_date3 TEXT
);

-- Table: gai_dmstech
CREATE TABLE gai_dmstech (
    gs_index INTEGER PRIMARY KEY AUTOINCREMENT,
    gs_id NUMERIC NOT NULL,
    gs_type INTEGER NOT NULL,
    gs_chr1 TEXT NOT NULL,
    gs_chr2 TEXT,
    gs_chr3 TEXT,
    gs_chr4 TEXT,
    gs_chr5 TEXT,
    gs_chx1 TEXT,
    gs_chx2 TEXT,
    gs_chx3 TEXT,
    gs_int1 INTEGER,
    gs_int2 INTEGER,
    gs_int3 INTEGER,
    gs_date1 TEXT,
    gs_date2 TEXT,
    gs_date3 TEXT,
    gs_consignor_sig BLOB,
    gs_driver_sig BLOB,
    gs_security2 TEXT
);

-- Table: gai_lock
CREATE TABLE gai_lock (
    gl_index INTEGER PRIMARY KEY AUTOINCREMENT,
    gl_id INTEGER NOT NULL,
    gl_ordnum INTEGER NOT NULL,
    gl_partnum TEXT NOT NULL,
    gl_userlot TEXT NOT NULL,
    gl_username TEXT,
    gl_qty1 INTEGER,
    gl_qty2 INTEGER,
    gl_qty3 INTEGER,
    gl_datel TEXT,
    gl_date1 TEXT,
    gl_date2 TEXT,
    gl_notes1 TEXT,
    gl_notes2 TEXT,
    gl_chr1 TEXT,
    gl_chr2 TEXT,
    gl_chx1 TEXT,
    gl_chx2 TEXT,
    gl_int1 INTEGER,
    gl_int2 INTEGER,
    gl_dec1 NUMERIC,
    gl_dec2 NUMERIC,
    gl_date3 TEXT,
    gl_date4 TEXT
);

-- Table: gai_paway
CREATE TABLE gai_paway (
    gp_index INTEGER PRIMARY KEY AUTOINCREMENT,
    gp_id INTEGER NOT NULL,
    gp_ordnum INTEGER NOT NULL,
    gp_codenum TEXT NOT NULL,
    gp_userlot TEXT NOT NULL,
    gp_qty INTEGER,
    gp_qty1 INTEGER,
    gp_qty2 INTEGER,
    gp_qty3 INTEGER,
    gp_lo TEXT,
    gp_lo1 TEXT,
    gp_lo2 TEXT,
    gp_lo3 TEXT,
    gp_datep TEXT,
    gp_date1 TEXT,
    gp_date2 TEXT,
    gp_date3 TEXT,
    gp_chr1 TEXT,
    gp_chr2 TEXT,
    gp_chr3 TEXT,
    gp_int1 INTEGER,
    gp_int2 INTEGER,
    gp_int3 INTEGER,
    gp_dec1 NUMERIC,
    gp_dec2 NUMERIC,
    gp_dec3 NUMERIC,
    gp_chx1 TEXT,
    gp_chx2 TEXT,
    gp_chx3 TEXT,
    gp_ima1 BLOB,
    gp_ima2 BLOB,
    gp_ima3 BLOB
);

-- Table: gai_putaway
CREATE TABLE gai_putaway (
    gp_id INTEGER PRIMARY KEY AUTOINCREMENT,
    gp_type TEXT,
    gp_orderid NUMERIC,
    gp_prcodenum TEXT,
    gp_loid INTEGER,
    gp_userlot TEXT,
    gp_masterlot INTEGER,
    gp_quant INTEGER
);

-- Table: gai_rddetail
CREATE TABLE gai_rddetail (
    rdd_id INTEGER PRIMARY KEY AUTOINCREMENT,
    rdd_rdhid INTEGER,
    rdd_ingname TEXT,
    rdd_code TEXT,
    rdd_formulapct NUMERIC,
    rdd_ingredienttype TEXT,
    rdd_supplierlotinfo TEXT,
    rdd_chemstate TEXT,
    rdd_density NUMERIC,
    rdd_abvpercent NUMERIC,
    rdd_juicename TEXT,
    rdd_brix NUMERIC,
    rdd_rmc NUMERIC
);

-- Table: gai_rdheader
CREATE TABLE gai_rdheader (
    rdh_id INTEGER PRIMARY KEY AUTOINCREMENT,
    rdh_formulaname TEXT,
    rdh_code TEXT,
    rdh_datecreated TEXT,
    rdh_version INTEGER,
    rdh_productyield NUMERIC,
    rdh_targetabv NUMERIC,
    rdh_targetco2 NUMERIC,
    rdh_targetta NUMERIC,
    rdh_targetph NUMERIC,
    rdh_targetdensity NUMERIC,
    rdh_processinginstr TEXT,
    rdh_targetbrix NUMERIC,
    rdh_waterdensity NUMERIC,
    rdh_productdensity NUMERIC,
    rdh_solutionprocessinstr TEXT
);

-- Table: gai_ReservedLocations
CREATE TABLE gai_ReservedLocations (
    gr_id INTEGER PRIMARY KEY AUTOINCREMENT,
    gr_loid INTEGER,
    gr_orderid NUMERIC,
    gr_resdate TEXT,
    gr_restime TEXT
);

-- Table: gai_scheduler
CREATE TABLE gai_scheduler (
    gs_index INTEGER PRIMARY KEY AUTOINCREMENT,
    gs_id NUMERIC NOT NULL,
    gs_ordnum INTEGER NOT NULL,
    gs_dock TEXT,
    gs_datestart TEXT,
    gs_dateend TEXT,
    gs_dockm TEXT,
    gs_company TEXT,
    gs_carrier TEXT,
    gs_driver TEXT,
    gs_notes TEXT,
    gs_datechkin TEXT,
    gs_status TEXT,
    gs_appid TEXT NOT NULL,
    gs_forkop TEXT,
    gs_chr1 TEXT,
    gs_chr2 TEXT,
    gs_chr3 TEXT,
    gs_num1 INTEGER,
    gs_num2 INTEGER,
    gs_num3 INTEGER,
    gs_dec1 NUMERIC,
    gs_dec2 NUMERIC,
    gs_dec3 NUMERIC,
    gs_log1 INTEGER,
    gs_log2 INTEGER,
    gs_log3 INTEGER,
    gs_img1 BLOB,
    gs_img2 BLOB,
    gs_img3 BLOB,
    gs_date1 TEXT,
    gs_date2 TEXT,
    gs_date3 TEXT,
    gs_picker TEXT,
    gs_pickerout TEXT,
    gs_pickerin TEXT,
    gs_auditor TEXT,
    gs_auditorout TEXT,
    gs_auditorin TEXT,
    gs_assembler TEXT,
    gs_assemblerout TEXT,
    gs_assemblerin TEXT,
    gs_chr4 TEXT,
    gs_chr5 TEXT,
    gs_chr6 TEXT,
    gs_num4 INTEGER,
    gs_num5 INTEGER,
    gs_num6 INTEGER,
    gs_dec4 NUMERIC,
    gs_dec5 NUMERIC,
    gs_dec6 INTEGER,
    gs_log4 INTEGER,
    gs_log5 INTEGER,
    gs_log6 INTEGER,
    gs_img4 BLOB,
    gs_img5 BLOB,
    gs_img6 BLOB,
    gs_date4 TEXT,
    gs_date5 TEXT,
    gs_date6 TEXT,
    gs_pronum INTEGER,
    gs_pallets INTEGER,
    gs_nwt NUMERIC,
    gs_gwt NUMERIC,
    gs_notesict TEXT
);

-- Table: gai_scheduler_old
CREATE TABLE gai_scheduler_old (
    gs_id NUMERIC NOT NULL,
    gs_ordnum INTEGER NOT NULL,
    gs_dock TEXT,
    gs_datestart TEXT,
    gs_dateend TEXT,
    gs_dockm TEXT,
    gs_company TEXT,
    gs_carrier TEXT,
    gs_driver TEXT,
    gs_notes TEXT,
    gs_datechkin TEXT,
    gs_status TEXT,
    gs_appid TEXT,
    gs_forkop TEXT,
    gs_chr1 TEXT,
    gs_chr2 TEXT,
    gs_chr3 TEXT,
    gs_num1 INTEGER,
    gs_num2 INTEGER,
    gs_num3 INTEGER,
    gs_dec1 NUMERIC,
    gs_dec2 NUMERIC,
    gs_dec3 NUMERIC,
    gs_log1 INTEGER,
    gs_log2 INTEGER,
    gs_log3 INTEGER,
    gs_img1 BLOB,
    gs_img2 BLOB,
    gs_img3 BLOB,
    gs_date1 TEXT,
    gs_date2 TEXT,
    gs_date3 TEXT,
    gs_picker TEXT,
    gs_pickerout TEXT,
    gs_pickerin TEXT
);

-- Table: gai_scheduler_tmp
CREATE TABLE gai_scheduler_tmp (
    gs_index INTEGER PRIMARY KEY AUTOINCREMENT,
    gs_id NUMERIC NOT NULL,
    gs_ordnum INTEGER NOT NULL,
    gs_dock TEXT,
    gs_datestart TEXT,
    gs_dateend TEXT,
    gs_dockm TEXT,
    gs_company TEXT,
    gs_carrier TEXT,
    gs_driver TEXT,
    gs_notes TEXT,
    gs_datechkin TEXT,
    gs_status TEXT,
    gs_appid TEXT NOT NULL,
    gs_forkop TEXT,
    gs_chr1 TEXT,
    gs_chr2 TEXT,
    gs_chr3 TEXT,
    gs_num1 INTEGER,
    gs_num2 INTEGER,
    gs_num3 INTEGER,
    gs_dec1 NUMERIC,
    gs_dec2 NUMERIC,
    gs_dec3 NUMERIC,
    gs_log1 INTEGER,
    gs_log2 INTEGER,
    gs_log3 INTEGER,
    gs_img1 BLOB,
    gs_img2 BLOB,
    gs_img3 BLOB,
    gs_date1 TEXT,
    gs_date2 TEXT,
    gs_date3 TEXT,
    gs_picker TEXT,
    gs_pickerout TEXT,
    gs_pickerin TEXT,
    gs_auditor TEXT,
    gs_auditorout TEXT,
    gs_auditorin TEXT,
    gs_assembler TEXT,
    gs_assemblerout TEXT,
    gs_assemblerin TEXT,
    gs_chr4 TEXT,
    gs_chr5 TEXT,
    gs_chr6 TEXT,
    gs_num4 INTEGER,
    gs_num5 INTEGER,
    gs_num6 INTEGER,
    gs_dec4 NUMERIC,
    gs_dec5 NUMERIC,
    gs_dec6 INTEGER,
    gs_log4 INTEGER,
    gs_log5 INTEGER,
    gs_log6 INTEGER,
    gs_img4 BLOB,
    gs_img5 BLOB,
    gs_img6 BLOB,
    gs_date4 TEXT,
    gs_date5 TEXT,
    gs_date6 TEXT,
    gs_pronum INTEGER,
    gs_pallets INTEGER,
    gs_nwt NUMERIC,
    gs_gwt NUMERIC,
    gs_notesict TEXT,
    gs_stagloc TEXT
);

-- Table: gai_shipping_rate
CREATE TABLE gai_shipping_rate (
    sr_id INTEGER PRIMARY KEY AUTOINCREMENT,
    sr_source TEXT,
    sr_destination TEXT,
    sr_rate NUMERIC,
    sr_startdate TEXT,
    sr_enddate TEXT
);

-- Table: gai_singlestrengthconversions
CREATE TABLE gai_singlestrengthconversions (
    ssc_id INTEGER PRIMARY KEY AUTOINCREMENT,
    ssc_Fruit TEXT,
    ssc_BrixAtSingleStrength TEXT,
    ssc_Ref TEXT
);

-- Table: gai_singlestrengthconversions_old
CREATE TABLE gai_singlestrengthconversions_old (
    Fruit TEXT,
    BrixAtSingleStrength TEXT,
    Ref TEXT
);

-- Table: gai_sr_destinations
CREATE TABLE gai_sr_destinations (
    sd_id INTEGER PRIMARY KEY AUTOINCREMENT,
    sd_name TEXT
);

-- Table: gai_sr_sources
CREATE TABLE gai_sr_sources (
    sc_id INTEGER PRIMARY KEY AUTOINCREMENT,
    sc_name TEXT
);

-- Table: gai_syslogs
CREATE TABLE gai_syslogs (
    gs_index INTEGER NOT NULL,
    gs_id NUMERIC NOT NULL,
    gs_sys TEXT NOT NULL,
    gs_user TEXT NOT NULL,
    gs_in TEXT NOT NULL,
    gs_out TEXT
);

-- Table: gp_f011head
CREATE TABLE gp_f011head (
    gf_index INTEGER NOT NULL,
    gf_id NUMERIC NOT NULL,
    gf_jobnum INTEGER NOT NULL,
    gf_fdate TEXT NOT NULL,
    gf_1s TEXT,
    gf_1sdate TEXT,
    gf_2s TEXT,
    gf_2sdate TEXT,
    gf_oper TEXT,
    gf_chr1 TEXT,
    gf_chr2 TEXT,
    gf_chx1 TEXT,
    gf_chx2 TEXT,
    gf_date1 TEXT,
    gf_date2 TEXT,
    gf_dec1 NUMERIC,
    gf_dec2 NUMERIC,
    gf_int1 INTEGER,
    gf_int2 INTEGER,
    gf_ima1 BLOB,
    gf_ima2 BLOB
);

-- Table: gp_prodrep
CREATE TABLE gp_prodrep (
    gf_index INTEGER PRIMARY KEY AUTOINCREMENT,
    gf_id NUMERIC NOT NULL,
    gf_form INTEGER NOT NULL,
    gf_sec INTEGER NOT NULL,
    gf_jobdate TEXT NOT NULL,
    gf_jobnum INTEGER NOT NULL,
    gf_f1 TEXT,
    gf_f2 TEXT,
    gf_f3 TEXT,
    gf_f4 TEXT,
    gf_f5 TEXT,
    gf_f6 TEXT,
    gf_f7 TEXT,
    gf_f8 TEXT,
    gf_f9 TEXT,
    gf_f10 TEXT,
    gf_chr1 TEXT,
    gf_chr2 TEXT,
    gf_chr3 TEXT,
    gf_chx1 TEXT,
    gf_chx2 TEXT,
    gf_chx3 TEXT,
    gf_int1 INTEGER,
    gf_int2 INTEGER,
    gf_int3 INTEGER,
    gf_date1 TEXT,
    gf_date2 TEXT,
    gf_date3 TEXT,
    gf_ima1 BLOB,
    gf_ima2 BLOB,
    gf_ima3 BLOB
);

-- Table: gp_scheduler
CREATE TABLE gp_scheduler (
    gp_index INTEGER NOT NULL,
    gp_id NUMERIC NOT NULL,
    gp_startdate TEXT,
    gp_enddate TEXT,
    gp_jobnum INTEGER NOT NULL,
    gp_filling NUMERIC,
    gp_jobqty NUMERIC,
    gp_unit TEXT,
    gp_pounds NUMERIC,
    gp_spec TEXT,
    gp_product TEXT,
    gp_notes TEXT,
    gp_remarks TEXT,
    gp_backc TEXT,
    gp_forec TEXT,
    gp_chr1 TEXT,
    gp_chr2 TEXT,
    gp_chr3 TEXT,
    gp_chx1 TEXT,
    gp_chx2 TEXT,
    gp_chx3 TEXT,
    gp_dec1 NUMERIC,
    gp_dec2 NUMERIC,
    gp_dec3 NUMERIC,
    gp_num1 NUMERIC,
    gp_num2 NUMERIC,
    gp_num3 NUMERIC,
    gp_date1 TEXT,
    gp_date2 TEXT,
    gp_date3 TEXT,
    gp_log1 INTEGER,
    gp_log2 INTEGER,
    gp_log3 INTEGER,
    gp_image1 BLOB,
    gp_image2 BLOB,
    gp_image3 BLOB
);

-- Table: gw_prefixes
CREATE TABLE gw_prefixes (
    pf_id INTEGER NOT NULL,
    pf_udfid INTEGER,
    pf_veid INTEGER,
    pf_prefix TEXT
);

-- Table: liberation_tariff
CREATE TABLE liberation_tariff (
    Country_ID TEXT NOT NULL,
    Country_name TEXT NOT NULL,
    Country_code TEXT NOT NULL,
    Country_Group TEXT,
    Liberation_tariff NUMERIC NOT NULL,
    Effective_Date TEXT,
    New_liberation NUMERIC
);

-- Table: Shipping_Rate
CREATE TABLE Shipping_Rate (
    sr_id INTEGER PRIMARY KEY AUTOINCREMENT,
    sr_source TEXT NOT NULL,
    sr_destination TEXT NOT NULL,
    sr_rate REAL NOT NULL,
    sr_startdate TEXT NOT NULL,
    sr_enddate TEXT
);

-- Table: USDABrandedFood2
CREATE TABLE USDABrandedFood2 (
    fdc_id REAL,
    brand_owner TEXT,
    brand_name TEXT,
    description TEXT,
    subbrand_name TEXT,
    gtin_upc REAL,
    ingredients TEXT,
    branded_food_category TEXT,
    food_category_id TEXT,
    publication_date TEXT
);

-- Table: USDABrandedFoodIngredients
CREATE TABLE USDABrandedFoodIngredients (
    fdc_id REAL,
    brand_owner TEXT,
    brand_name TEXT,
    description TEXT,
    subbrand_name TEXT,
    gtin_upc REAL,
    ingredient TEXT,
    branded_food_category TEXT,
    food_category_id TEXT,
    publication_date TEXT
);

-- Table: USDABrandedFoods
CREATE TABLE USDABrandedFoods (
    fdc_id REAL,
    brand_owner TEXT,
    brand_name TEXT,
    description TEXT,
    subbrand_name TEXT,
    gtin_upc REAL,
    ingredients TEXT,
    branded_food_category TEXT,
    food_category_id TEXT,
    publication_date TEXT
);

-- Table: acuity_appointments
CREATE TABLE acuity_appointments (
    id INTEGER NOT NULL,
    firstName TEXT NOT NULL,
    lastName TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    date TEXT,
    time TEXT,
    endTime TEXT,
    dateCreated TEXT,
    datetimeCreated TEXT,
    datetime TEXT,
    price NUMERIC NOT NULL,
    priceSold NUMERIC NOT NULL,
    paid TEXT,
    amountPaid NUMERIC NOT NULL,
    type TEXT,
    appointmentTypeID INTEGER,
    classID INTEGER,
    category TEXT,
    duration INTEGER,
    calendar TEXT,
    calendarID INTEGER,
    certificate TEXT,
    confirmationPage TEXT,
    confirmationPagePaymentLink TEXT,
    location TEXT,
    notes TEXT,
    timezone TEXT,
    calendarTimezone TEXT,
    canceled INTEGER NOT NULL,
    canClientCancel INTEGER NOT NULL,
    canClientReschedule INTEGER NOT NULL,
    labels TEXT,
    formsText TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

/* DISABLED: acuity_forms and acuity_form_values use composite primary/foreign keys
 * which are not supported by the DDL parser. See GitHub issue for enhancement.
-- Table: acuity_forms
CREATE TABLE acuity_forms (
    id INTEGER NOT NULL,
    appointment_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

-- Table: acuity_form_values
CREATE TABLE acuity_form_values (
    id INTEGER NOT NULL,
    form_id INTEGER NOT NULL,
    appointment_id INTEGER NOT NULL,
    fieldID INTEGER NOT NULL,
    value TEXT,
    name TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
END DISABLED */
